GET https://www.omdbapi.com/?apikey=450e73c0&s=frits+the+cat HTTP/1.1
###

GET https://www.omdbapi.com/?apikey=450e73c0&s=watchman&type=series HTTP/1.1
###

GET https://www.omdbapi.com/?apikey=450e73c0&s=pirates+of+the+carebbian HTTP/1.1
###

GET https://www.omdbapi.com/?apikey=450e73c0&s=lord+of+the+ring HTTP/1.1
###

GET https://www.omdbapi.com/?apikey=450e73c0&s=nightmare HTTP/1.1
###

//solo episodes
GET https://www.omdbapi.com/?apikey=450e73c0&s=nightmare&type=episode HTTP/1.1
###

//solo series
GET https://www.omdbapi.com/?apikey=450e73c0&s=nightmare&type=series HTTP/1.1
###

//solo games
GET https://www.omdbapi.com/?apikey=450e73c0&s=nightmare&type=game HTTP/1.1
###

//solo movies
GET https://www.omdbapi.com/?apikey=450e73c0&s=nightmare&type=movie HTTP/1.1
###

//solo movies page 1
GET https://www.omdbapi.com/?apikey=450e73c0&s=nightmare&type=movie&page=1 HTTP/1.1
###

//solo movies page 2
GET https://www.omdbapi.com/?apikey=450e73c0&s=nightmare&type=movie&page=2 HTTP/1.1
###

//solo movies in ordine di anno
GET https://www.omdbapi.com/?apikey=450e73c0&s=nightmare&type=movie&y= HTTP/1.1
###

GET https://www.omdbapi.com/?apikey=450e73c0&s=tropic%20thunder HTTP/1.1
###

GET https://www.omdbapi.com/?apikey=450e73c0&s=sin%20city&type=movie HTTP/1.1
###

GET https://www.omdbapi.com/?apikey=450e73c0&t=dagon&type=movie HTTP/1.1
###

GET https://www.omdbapi.com/?apikey=450e73c0&t=interstellar&type=movie HTTP/1.1
###

GET https://www.omdbapi.com/?apikey=450e73c0&i=tt0102511 HTTP/1.1


//{"Title":"A Nightmare on Elm Street","Year":"2010","imdbID":"tt1179056","Type":"movie","Poster":"https://m.media-amazon.com/images/M/MV5BODIxMTQ0NTIxM15BMl5BanBnXkFtZTcwMzY1NDAyMw@@._V1_SX300.jpg"}*/




//sito

//dagon

GET https://www.omdbapi.com/?apikey=450e73c0&t=dagon&type=movie HTTP/1.1
###

//the onion movie

GET https://www.omdbapi.com/?apikey=450e73c0&t=the%20onion%20movie&type=movie HTTP/1.1
###

//superhero
GET https://www.omdbapi.com/?apikey=450e73c0&s=superhero&type=movie HTTP/1.1
###

//SLC punk
GET https://www.omdbapi.com/?apikey=450e73c0&t=slc%20punk&type=movie HTTP/1.1
###

//silent hill
GET https://www.omdbapi.com/?apikey=450e73c0&t=silent%20hill&type=movie HTTP/1.1
###

//the warriors
GET https://www.omdbapi.com/?apikey=450e73c0&t=the%20warriors&type=movie HTTP/1.1
###

//
GET https://www.omdbapi.com/?apikey=450e73c0&t=%20&type=movie HTTP/1.1
###

//
GET https://www.omdbapi.com/?apikey=450e73c0&t=%20&type=movie HTTP/1.1
###

//
GET https://www.omdbapi.com/?apikey=450e73c0&t=%20&type=movie HTTP/1.1
###

//
GET https://www.omdbapi.com/?apikey=450e73c0&t=%20&type=movie HTTP/1.1
###


